[package]
name = "preserve_listserv"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "cookies"] }
scraper = "0.22.0"
dotenv = "0.15"
rust-loguru = "0.1.8"
lock_api = "0.4"
parking_lot = "0.12"
